from .. import i18n as i18n
from ..utils import str_coercible as str_coercible

@str_coercible
class Country:
    code: str

    def __init__(self, code_or_country: str | Country) -> None: ...
    @property
    def name(self) -> str: ...
    @classmethod
    def validate(cls, code: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __unicode__(self) -> str: ...
