from .. import ImproperlyConfigured as ImproperlyConfigured, i18n as i18n
from ..utils import str_coercible as str_coercible

@str_coercible
class Currency:
    def __init__(self, code: str | Currency) -> None: ...
    @classmethod
    def validate(self, code: str) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def name(self) -> str: ...
